// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: card.query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFlashcard = `-- name: CreateFlashcard :one
INSERT INTO flashcard (
  deck_id, question, answer, next_review_date,
  interval, repetitions, easiness_factor
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING flashcard_id, deck_id, question, answer, next_review_date, interval, repetitions, easiness_factor, created_at, updated_at, is_archived
`

type CreateFlashcardParams struct {
	DeckID         int32           `json:"deck_id"`
	Question       string          `json:"question"`
	Answer         string          `json:"answer"`
	NextReviewDate sql.NullTime    `json:"next_review_date"`
	Interval       sql.NullInt32   `json:"interval"`
	Repetitions    sql.NullInt32   `json:"repetitions"`
	EasinessFactor sql.NullFloat64 `json:"easiness_factor"`
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, createFlashcard,
		arg.DeckID,
		arg.Question,
		arg.Answer,
		arg.NextReviewDate,
		arg.Interval,
		arg.Repetitions,
		arg.EasinessFactor,
	)
	var i Flashcard
	err := row.Scan(
		&i.FlashcardID,
		&i.DeckID,
		&i.Question,
		&i.Answer,
		&i.NextReviewDate,
		&i.Interval,
		&i.Repetitions,
		&i.EasinessFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsArchived,
	)
	return i, err
}

const deleteFlashcard = `-- name: DeleteFlashcard :one
DELETE FROM flashcard
WHERE flashcard_id = $1
RETURNING flashcard_id, deck_id, question, answer, next_review_date, interval, repetitions, easiness_factor, created_at, updated_at, is_archived
`

func (q *Queries) DeleteFlashcard(ctx context.Context, flashcardID int32) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, deleteFlashcard, flashcardID)
	var i Flashcard
	err := row.Scan(
		&i.FlashcardID,
		&i.DeckID,
		&i.Question,
		&i.Answer,
		&i.NextReviewDate,
		&i.Interval,
		&i.Repetitions,
		&i.EasinessFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsArchived,
	)
	return i, err
}

const getDeckID = `-- name: GetDeckID :one
SELECT deck_id FROM flashcard
WHERE flashcard_id = $1 LIMIT 1
`

func (q *Queries) GetDeckID(ctx context.Context, flashcardID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDeckID, flashcardID)
	var deck_id int32
	err := row.Scan(&deck_id)
	return deck_id, err
}

const getFlashcard = `-- name: GetFlashcard :one
SELECT flashcard_id, deck_id, question, answer, next_review_date, interval, repetitions, easiness_factor, created_at, updated_at, is_archived FROM flashcard
WHERE flashcard_id = $1 LIMIT 1
`

func (q *Queries) GetFlashcard(ctx context.Context, flashcardID int32) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, getFlashcard, flashcardID)
	var i Flashcard
	err := row.Scan(
		&i.FlashcardID,
		&i.DeckID,
		&i.Question,
		&i.Answer,
		&i.NextReviewDate,
		&i.Interval,
		&i.Repetitions,
		&i.EasinessFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsArchived,
	)
	return i, err
}

const listFlashcardsByDeck = `-- name: ListFlashcardsByDeck :many
SELECT flashcard_id, deck_id, question, answer, next_review_date, interval, repetitions, easiness_factor, created_at, updated_at, is_archived FROM flashcard
WHERE deck_id = $1
ORDER BY created_at
`

func (q *Queries) ListFlashcardsByDeck(ctx context.Context, deckID int32) ([]Flashcard, error) {
	rows, err := q.db.QueryContext(ctx, listFlashcardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flashcard
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.FlashcardID,
			&i.DeckID,
			&i.Question,
			&i.Answer,
			&i.NextReviewDate,
			&i.Interval,
			&i.Repetitions,
			&i.EasinessFactor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlashcard = `-- name: UpdateFlashcard :one
UPDATE flashcard
SET question = $1, answer = $2, next_review_date = $3,
    interval = $4, repetitions = $5, easiness_factor = $6,
    updated_at = NOW()
WHERE flashcard_id = $7
RETURNING flashcard_id, deck_id, question, answer, next_review_date, interval, repetitions, easiness_factor, created_at, updated_at, is_archived
`

type UpdateFlashcardParams struct {
	Question       string          `json:"question"`
	Answer         string          `json:"answer"`
	NextReviewDate sql.NullTime    `json:"next_review_date"`
	Interval       sql.NullInt32   `json:"interval"`
	Repetitions    sql.NullInt32   `json:"repetitions"`
	EasinessFactor sql.NullFloat64 `json:"easiness_factor"`
	FlashcardID    int32           `json:"flashcard_id"`
}

func (q *Queries) UpdateFlashcard(ctx context.Context, arg UpdateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, updateFlashcard,
		arg.Question,
		arg.Answer,
		arg.NextReviewDate,
		arg.Interval,
		arg.Repetitions,
		arg.EasinessFactor,
		arg.FlashcardID,
	)
	var i Flashcard
	err := row.Scan(
		&i.FlashcardID,
		&i.DeckID,
		&i.Question,
		&i.Answer,
		&i.NextReviewDate,
		&i.Interval,
		&i.Repetitions,
		&i.EasinessFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsArchived,
	)
	return i, err
}
