// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: deck.query.sql

package db

import (
	"context"
	"database/sql"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO deck (
  account_id, title
) VALUES (
  $1, $2
)
RETURNING deck_id, account_id, title, created_at
`

type CreateDeckParams struct {
	AccountID sql.NullInt32 `json:"account_id"`
	Title     string        `json:"title"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck, arg.AccountID, arg.Title)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.AccountID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM deck
WHERE deck_id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, deckID int32) error {
	_, err := q.db.ExecContext(ctx, deleteDeck, deckID)
	return err
}

const getDeck = `-- name: GetDeck :one
SELECT deck_id, account_id, title, created_at FROM deck
WHERE deck_id = $1 LIMIT 1
`

func (q *Queries) GetDeck(ctx context.Context, deckID int32) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, deckID)
	var i Deck
	err := row.Scan(
		&i.DeckID,
		&i.AccountID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listDecksByAccount = `-- name: ListDecksByAccount :many
SELECT deck_id, account_id, title, created_at FROM deck
WHERE account_id = $1
ORDER BY title
`

func (q *Queries) ListDecksByAccount(ctx context.Context, accountID sql.NullInt32) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecksByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.DeckID,
			&i.AccountID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeckTitle = `-- name: UpdateDeckTitle :exec
UPDATE deck SET title = $1
WHERE deck_id = $2
`

type UpdateDeckTitleParams struct {
	Title  string `json:"title"`
	DeckID int32  `json:"deck_id"`
}

func (q *Queries) UpdateDeckTitle(ctx context.Context, arg UpdateDeckTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateDeckTitle, arg.Title, arg.DeckID)
	return err
}
