// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	AccountID    int32        `json:"account_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Deck struct {
	DeckID    int32        `json:"deck_id"`
	AccountID int32        `json:"account_id"`
	Title     string       `json:"title"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Flashcard struct {
	FlashcardID    int32           `json:"flashcard_id"`
	DeckID         int32           `json:"deck_id"`
	Question       string          `json:"question"`
	Answer         string          `json:"answer"`
	NextReviewDate sql.NullTime    `json:"next_review_date"`
	Interval       sql.NullInt32   `json:"interval"`
	Repetitions    sql.NullInt32   `json:"repetitions"`
	EasinessFactor sql.NullFloat64 `json:"easiness_factor"`
	CreatedAt      sql.NullTime    `json:"created_at"`
	UpdatedAt      sql.NullTime    `json:"updated_at"`
	IsArchived     sql.NullBool    `json:"is_archived"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	AccountID    int32     `json:"account_id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
